---
title: "STA426_Exercise01_BO"
author: "Barryette Oberholzer"
date: "15 9 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Sampling the log-normal distribution

<br>

Sampling 100 values from a log-normal distribution with the function `rlnorm` using a **mean of 1** and a **standard deviation of 0.25**

<br>

```{r out.width=c("50%","50%"), out.height=c("50%","50%"), fig.show='hold'}

# Sampling from a log normal distribution
x = rlnorm(n = 100, meanlog = 1, sdlog = 0.25)

# Plotting the sample as counts in a histogram
hist(x, probability = FALSE)

# Plotting the sample as proportions in a histogram 
hist(x, probability = TRUE)

# plotting the sample as counts on a log-scaled y-axis
hist.data = hist(x, plot=F)
hist.data$counts = log(hist.data$counts)
plot(hist.data, ylab='log(Frequency)')

# plotting the sample as a smooth density curve
plot(density(x))







```

<br>

### Resulting distribution

The resulting distribution has a **mean of `r signif(mean(x),2)`** and a **variance of `r signif(var(x),2)`**. 

<br><br><br><br>